{"packages":{"villfa\/tryagain":{"1.0.0":{"name":"villfa\/tryagain","description":"The TryAgain library permits to call a function again if the result is wrong.","keywords":["library","error handling"],"homepage":"https:\/\/github.com\/villfa\/TryAgain","version":"1.0.0","version_normalized":"1.0.0.0","license":["MIT"],"authors":[{"name":"Fabien Villepinte","email":"fabien.villepinte@gmail.com"}],"source":{"type":"git","url":"https:\/\/github.com\/villfa\/TryAgain.git","reference":"4808c1e09a8f0087d6c5164dc8d879bb8ebebd29"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/villfa\/TryAgain\/zipball\/4808c1e09a8f0087d6c5164dc8d879bb8ebebd29","reference":"4808c1e09a8f0087d6c5164dc8d879bb8ebebd29","shasum":""},"type":"library","time":"2013-04-20T17:06:06+00:00","autoload":{"psr-0":{"TryAgain\\":"."}},"require":{"php":">=5.3.3"},"require-dev":{"mockery\/mockery":">=0.8.0"},"uid":49964},"dev-master":{"name":"villfa\/tryagain","description":"The TryAgain library permits to call a function again if the result is wrong.","keywords":["library","error handling"],"homepage":"https:\/\/github.com\/villfa\/TryAgain","version":"dev-master","version_normalized":"9999999-dev","license":["MIT"],"authors":[{"name":"Fabien Villepinte","email":"fabien.villepinte@gmail.com"}],"source":{"type":"git","url":"https:\/\/github.com\/villfa\/TryAgain.git","reference":"4808c1e09a8f0087d6c5164dc8d879bb8ebebd29"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/villfa\/TryAgain\/zipball\/4808c1e09a8f0087d6c5164dc8d879bb8ebebd29","reference":"4808c1e09a8f0087d6c5164dc8d879bb8ebebd29","shasum":""},"type":"library","time":"2013-04-20T17:06:06+00:00","autoload":{"psr-0":{"TryAgain\\":"."}},"require":{"php":">=5.3.3"},"require-dev":{"mockery\/mockery":">=0.8.0"},"uid":49944}}}}